import { type Load } from "@/lib/types";

export const MOCK_LOADS: Load[] = [
  {
    id: "TLK-1001",
    originProvince: "Haut-Katanga",
    originCity: "Lubumbashi",
    destinationProvince: "Kinshasa",
    destinationCity: "Kinshasa",
    equipment: "Dry Van",
    lengthFt: 40,
    weightKg: 18000,
    rateUsd: 5200,
    postedHoursAgo: 2,
    pickupWindow: "Aujourd’hui / Demain",
    commodity: "Biens de consommation",
    company: "Toleka Dispatch",
  },
  {
    id: "TLK-1002",
    originProvince: "Lualaba",
    originCity: "Kolwezi",
    destinationProvince: "Haut-Katanga",
    destinationCity: "Lubumbashi",
    equipment: "Flatbed",
    lengthFt: 48,
    weightKg: 24000,
    rateUsd: 1450,
    postedHoursAgo: 5,
    pickupWindow: "48h",
    commodity: "Matériel minier",
    company: "Kivu Logistics (mock)",
  },
  {
    id: "TLK-1003",
    originProvince: "Haut-Katanga",
    originCity: "Kasumbalesa",
    destinationProvince: "Zambie",
    destinationCity: "Ndola",
    equipment: "Dry Van",
    lengthFt: 40,
    weightKg: 16000,
    rateUsd: 1100,
    postedHoursAgo: 1,
    pickupWindow: "Aujourd’hui",
    commodity: "Pièces auto",
    company: "CrossBorder Freight (mock)",
  },
  {
    id: "TLK-1004",
    originProvince: "Haut-Katanga",
    originCity: "Likasi",
    destinationProvince: "Lualaba",
    destinationCity: "Kolwezi",
    equipment: "Flatbed",
    lengthFt: 45,
    weightKg: 22000,
    postedHoursAgo: 9,
    pickupWindow: "Cette semaine",
    commodity: "Sacs (vrac sur palette)",
    company: "CopperWay (mock)",
  },
  {
    id: "TLK-1005",
    originProvince: "Lualaba",
    originCity: "Kolwezi",
    destinationProvince: "Zambie",
    destinationCity: "Kitwe",
    equipment: "Container",
    lengthFt: 40,
    weightKg: 20000,
    rateUsd: 1700,
    postedHoursAgo: 7,
    pickupWindow: "24-72h",
    commodity: "Cuivre (conteneur)",
    company: "Lualaba Minerals (mock)",
  },
  {
    id: "TLK-1006",
    originProvince: "Haut-Katanga",
    originCity: "Lubumbashi",
    destinationProvince: "Kongo-Central",
    destinationCity: "Matadi",
    equipment: "Dry Van",
    lengthFt: 40,
    weightKg: 19000,
    rateUsd: 6000,
    postedHoursAgo: 12,
    pickupWindow: "Cette semaine",
    commodity: "Marchandises diverses",
    company: "Toleka Dispatch",
  },
  {
    id: "TLK-1007",
    originProvince: "Lualaba",
    originCity: "Dilolo",
    destinationProvince: "Angola",
    destinationCity: "Luanda",
    equipment: "Dry Van",
    lengthFt: 40,
    weightKg: 14000,
    postedHoursAgo: 4,
    pickupWindow: "48h",
    commodity: "Colis / cartons",
    company: "Atlantic Line (mock)",
  },
  {
    id: "TLK-1008",
    originProvince: "Haut-Katanga",
    originCity: "Kipushi",
    destinationProvince: "Haut-Katanga",
    destinationCity: "Lubumbashi",
    equipment: "Tanker",
    lengthFt: 35,
    weightKg: 26000,
    postedHoursAgo: 3,
    pickupWindow: "Aujourd’hui",
    commodity: "Carburant (bulk)",
    company: "FuelLink (mock)",
  },
  {
    id: "TLK-1009",
    originProvince: "Lualaba",
    originCity: "Kolwezi",
    destinationProvince: "Tanganyika",
    destinationCity: "Kalemie",
    equipment: "Flatbed",
    lengthFt: 48,
    weightKg: 23000,
    postedHoursAgo: 18,
    pickupWindow: "Cette semaine",
    commodity: "Matériaux de construction",
    company: "Great Lakes Haulage (mock)",
  },
  {
    id: "TLK-1010",
    originProvince: "Haut-Katanga",
    originCity: "Sakania",
    destinationProvince: "Zambie",
    destinationCity: "Lusaka",
    equipment: "Dry Van",
    lengthFt: 40,
    weightKg: 17000,
    postedHoursAgo: 6,
    pickupWindow: "24h",
    commodity: "Agroalimentaire (sec)",
    company: "BorderFast (mock)",
  },
  {
    id: "TLK-1011",
    originProvince: "Haut-Katanga",
    originCity: "Lubumbashi",
    destinationProvince: "Lualaba",
    destinationCity: "Kambove",
    equipment: "Lowboy",
    lengthFt: 53,
    weightKg: 32000,
    postedHoursAgo: 10,
    pickupWindow: "72h",
    commodity: "Engin (surbaissé)",
    company: "MineMove (mock)",
  },
  {
    id: "TLK-1012",
    originProvince: "Lualaba",
    originCity: "Kambove",
    destinationProvince: "Haut-Katanga",
    destinationCity: "Likasi",
    equipment: "Flatbed",
    lengthFt: 48,
    weightKg: 21000,
    postedHoursAgo: 14,
    pickupWindow: "Cette semaine",
    commodity: "Tuyaux / acier",
    company: "CopperWay (mock)",
  },
  {
    id: "TLK-1013",
    originProvince: "Haut-Katanga",
    originCity: "Lubumbashi",
    destinationProvince: "Zambie",
    destinationCity: "Kitwe",
    equipment: "Reefer",
    lengthFt: 40,
    weightKg: 12000,
    rateUsd: 1350,
    postedHoursAgo: 8,
    pickupWindow: "24-48h",
    commodity: "Produits frais",
    company: "ColdChain (mock)",
  },
  {
    id: "TLK-1014",
    originProvince: "Lualaba",
    originCity: "Kolwezi",
    destinationProvince: "Haut-Katanga",
    destinationCity: "Kasumbalesa",
    equipment: "Dry Van",
    lengthFt: 40,
    weightKg: 15000,
    rateUsd: 900,
    postedHoursAgo: 22,
    pickupWindow: "Cette semaine",
    commodity: "Consommables",
    company: "Katanga Traders (mock)",
  },
  {
    id: "TLK-1015",
    originProvince: "Haut-Katanga",
    originCity: "Likasi",
    destinationProvince: "Kinshasa",
    destinationCity: "Kinshasa",
    equipment: "Dry Van",
    lengthFt: 45,
    weightKg: 20000,
    rateUsd: 5400,
    postedHoursAgo: 20,
    pickupWindow: "Cette semaine",
    commodity: "Marchandises générales",
    company: "Toleka Dispatch",
  },
  {
    id: "TLK-1016",
    originProvince: "Lualaba",
    originCity: "Dilolo",
    destinationProvince: "Angola",
    destinationCity: "Soyo",
    equipment: "Container",
    lengthFt: 40,
    weightKg: 21000,
    postedHoursAgo: 11,
    pickupWindow: "72h",
    commodity: "Pièces industrielles",
    company: "Atlantic Line (mock)",
  },
  {
    id: "TLK-1017",
    originProvince: "Haut-Katanga",
    originCity: "Kasumbalesa",
    destinationProvince: "Zambie",
    destinationCity: "Lusaka",
    equipment: "Flatbed",
    lengthFt: 48,
    weightKg: 25000,
    postedHoursAgo: 13,
    pickupWindow: "48h",
    commodity: "Câbles / bobines",
    company: "CrossBorder Freight (mock)",
  },
  {
    id: "TLK-1018",
    originProvince: "Lualaba",
    originCity: "Kolwezi",
    destinationProvince: "Kongo-Central",
    destinationCity: "Matadi",
    equipment: "Dry Van",
    lengthFt: 40,
    weightKg: 18000,
    rateUsd: 6800,
    postedHoursAgo: 16,
    pickupWindow: "Cette semaine",
    commodity: "Matériel",
    company: "Lualaba Minerals (mock)",
  },
  {
    id: "TLK-1019",
    originProvince: "Haut-Katanga",
    originCity: "Lubumbashi",
    destinationProvince: "Tanganyika",
    destinationCity: "Kalemie",
    equipment: "Dry Van",
    lengthFt: 40,
    weightKg: 17000,
    postedHoursAgo: 19,
    pickupWindow: "Cette semaine",
    commodity: "Colis divers",
    company: "Great Lakes Haulage (mock)",
  },
  {
    id: "TLK-1020",
    originProvince: "Lualaba",
    originCity: "Kambove",
    destinationProvince: "Zambie",
    destinationCity: "Ndola",
    equipment: "Tanker",
    lengthFt: 35,
    weightKg: 28000,
    rateUsd: 1600,
    postedHoursAgo: 21,
    pickupWindow: "24-72h",
    commodity: "Acide (bulk) — mock",
    company: "MineMove (mock)",
  },
  {
    id: "TLK-1021",
    originProvince: "Haut-Katanga",
    originCity: "Kipushi",
    destinationProvince: "Zambie",
    destinationCity: "Kitwe",
    equipment: "Flatbed",
    lengthFt: 48,
    weightKg: 23000,
    postedHoursAgo: 15,
    pickupWindow: "Cette semaine",
    commodity: "Structures métalliques",
    company: "CopperWay (mock)",
  },
  {
    id: "TLK-1022",
    originProvince: "Haut-Katanga",
    originCity: "Sakania",
    destinationProvince: "Haut-Katanga",
    destinationCity: "Lubumbashi",
    equipment: "Dry Van",
    lengthFt: 40,
    weightKg: 15000,
    postedHoursAgo: 17,
    pickupWindow: "48h",
    commodity: "Textile",
    company: "BorderFast (mock)",
  },
  {
    id: "TLK-1023",
    originProvince: "Lualaba",
    originCity: "Kolwezi",
    destinationProvince: "Haut-Katanga",
    destinationCity: "Likasi",
    equipment: "Lowboy",
    lengthFt: 53,
    weightKg: 34000,
    rateUsd: 2200,
    postedHoursAgo: 23,
    pickupWindow: "72h",
    commodity: "Charge lourde (surbaissé)",
    company: "MineMove (mock)",
  },
  {
    id: "TLK-1024",
    originProvince: "Haut-Katanga",
    originCity: "Lubumbashi",
    destinationProvince: "Zambie",
    destinationCity: "Ndola",
    equipment: "Container",
    lengthFt: 40,
    weightKg: 19000,
    postedHoursAgo: 24,
    pickupWindow: "Cette semaine",
    commodity: "Conteneur mixte",
    company: "Toleka Dispatch",
  },
  {
    id: "TLK-1025",
    originProvince: "Lualaba",
    originCity: "Dilolo",
    destinationProvince: "Haut-Katanga",
    destinationCity: "Kasumbalesa",
    equipment: "Dry Van",
    lengthFt: 40,
    weightKg: 16000,
    postedHoursAgo: 26,
    pickupWindow: "Cette semaine",
    commodity: "Emballages / cartons",
    company: "Atlantic Line (mock)",
  },
  {
    id: "TLK-1026",
    originProvince: "Haut-Katanga",
    originCity: "Likasi",
    destinationProvince: "Zambie",
    destinationCity: "Lusaka",
    equipment: "Reefer",
    lengthFt: 40,
    weightKg: 11000,
    rateUsd: 1500,
    postedHoursAgo: 25,
    pickupWindow: "24-48h",
    commodity: "Fruits / légumes",
    company: "ColdChain (mock)",
  },
];

